Adding an update to remember to always update gvm

diff --git a/gvm b/gvm
--- a/gvm
+++ b/gvm
@@ -21,6 +21,7 @@ branch="master"
 
 # Persistent Configuration Values
 override=true
+alwaysUpdate=false
 
 
 
@@ -89,6 +90,52 @@ loadConfig() {
     fi
 }
 
+alwaysUpdateQ() {
+    printf "Would you like to always update? "
+
+    read -rp "[Yes: Y or y | No: Enter]? " yn
+
+    # Only trigger on `Y` or `y`
+    if [[ "$yn" == "Y" || "$yn" == "y" ]]
+    then
+        echo "alwaysUpdate=true" >> "$gvmroot/.config"
+    fi
+}
+
+update() {
+    curl -sL "$GVMURL" > .gvm.tmp
+                    
+    # shellcheck disable=SC2002
+    DOWNLOADEDSUM=$(cat .gvm.tmp | shasum -a 256)
+    
+    if [[ $DOWNLOADEDSUM != "$EXPECTEDSUM" ]]
+    then
+        printf "Checksum does not match new version of GVM [%s]\n" "$SCRIPTVERSION"
+        printf "Expected: %s\n" "$EXPECTEDSUM"
+        printf "Actual:   %s\n" "$DOWNLOADEDSUM"
+        exit 1
+    fi
+
+    if ! cat .gvm.tmp > "$0"
+    then
+        rm .gvm.tmp
+        printf "Failed to move new version of GVM [%s]\n" "$SCRIPTVERSION"
+        exit 1
+    fi
+    rm .gvm.tmp
+
+    printf "GVM [%s] has been updated\n" "$SCRIPTVERSION"
+    printf "%s\n" "$@"
+    if ! exec $0 "$@"
+    then 
+        printf "Failed to execute new version of GVM [%s]\n" "$SCRIPTVERSION"
+        exit 1
+    fi
+
+    printf "Successful update and execution"
+    exit 0
+}
+
 # fail accepts a string argument, prints it and exits with a non-zero exit code
 function fail() {
     printf "%s\n" "$1"
@@ -115,45 +162,20 @@ update() {
         then
             if [[ "$EXPECTEDSUM" != "" && $FILESUM != "$EXPECTEDSUM" ]]
             then
-
-                printf "New Version of GVM [%s] Available would you like to update? " "$SCRIPTVERSION"
-
-                read -rp "[Yes: Y or y | No: Enter]? " yn
-
-                # Only trigger on `Y` or `y`
-                if [[ "$yn" == "Y" || "$yn" == "y" ]]
+                if [[ $alwaysUpdate == true ]]
                 then
-                    curl -sL "$GVMURL" > .gvm.tmp
-                    
-                    # shellcheck disable=SC2002
-                    DOWNLOADEDSUM=$(cat .gvm.tmp | shasum -a 256)
-                    
-                    if [[ $DOWNLOADEDSUM != "$EXPECTEDSUM" ]]
+                    update
+                else
+                    printf "New Version of GVM [%s] Available would you like to update? " "$SCRIPTVERSION"
+
+                    read -rp "[Yes: Y or y | No: Enter]? " yn
+
+                    # Only trigger on `Y` or `y`
+                    if [[ "$yn" == "Y" || "$yn" == "y" ]]
                     then
-                        printf "Checksum does not match new version of GVM [%s]\n" "$SCRIPTVERSION"
-                        printf "Expected: %s\n" "$EXPECTEDSUM"
-                        printf "Actual:   %s\n" "$DOWNLOADEDSUM"
-                        exit 1
+                        alwaysUpdateQ
+                        update
                     fi
-
-                    if ! cat .gvm.tmp > "$0"
-                    then
-                        rm .gvm.tmp
-                        printf "Failed to move new version of GVM [%s]\n" "$SCRIPTVERSION"
-                        exit 1
-                    fi
-                    rm .gvm.tmp
-
-                    printf "GVM [%s] has been updated\n" "$SCRIPTVERSION"
-                    printf "%s\n" "$@"
-                    if ! exec $0 "$@"
-                    then 
-                        printf "Failed to execute new version of GVM [%s]\n" "$SCRIPTVERSION"
-                        exit 1
-                    fi
-
-                    printf "Successful update and execution"
-                    exit 0
                 fi
             fi
         fi
